Add check name to check constructor
mpounsett/nagiosplugin pull request #25
Opened 2020-02-25 07:06 UTC by simonmeggle

This allows to explicitly set the output prefix/check name at creation time or to clear it with name=None.
Omitting the name results in the default behaviour (output prefix = 1st resource name)

2021-11-25 18:13 UTC, mpounsett requested changes

2021-11-25 18:13 UTC, mpounsett commented on nagiosplugin/check.py
> +        resource's name. If *name* is None, so prefix is set at all.
There's a typo in this line.  ITYM:
```
        resource's name. If *name* is None, no prefix is set at all.
```

2021-11-25 18:13 UTC, mpounsett commented on nagiosplugin/output.py
> +            ' - ' + summary_str if summary_str else ''), 'status line').strip()
Is this directly related to the change in `check.py`?  It looks like an unrelated modification.

2022-02-06 18:59 UTC, mpounsett commented
@simonmeggle : Are you still interested in seeing this PR applied?  If so, could you respond to the comments above?  If I don't hear back in the next month or so I'll close the PR.

2022-02-07 11:09 UTC, simonmeggle commented
Honestly, I don't remember why I added the strip call. My PR will work also without it, I think.

2022-02-07 15:16 UTC, mpounsett commented
OK.  Can you fix that, and the other thing and update the PR?

2022-02-07 17:01 UTC, closed without merging

2022-02-07 17:50 UTC, mpounsett commented
Sorry about that @simonmeggle ... I was doing branch cleanup and it didn't occur to me that this open PR would be affected.  Once you clean up the requested changes above, please resubmit the PR to the `develop` branch.