Add check name to constructor
mpounsett/nagiosplugin pull request #46
Opened 2022-02-10 07:11 UTC by simonmeggle

As requested, I fixed the PR.

2022-02-12 16:23 UTC, mpounsett requested changes

2022-02-12 16:23 UTC, mpounsett commented on nagiosplugin/check.py
> +        resource's name. If *name* is None, so prefix is set at all.
Is this a typo?  ITYM:
```suggestion
        resource's name. If *name* is None, no prefix is set at all.
```

2022-02-14 07:52 UTC, simonmeggle commented on nagiosplugin/check.py
> +        resource's name. If *name* is None, so prefix is set at all.
(Yes, this is a typo.)

2022-02-15 16:23 UTC, mpounsett commented on nagiosplugin/check.py
> +        resource's name. If *name* is None, so prefix is set at all.
OK.  Do you want to push a change to your PR to fix it?  Once that's done I'll merge it in.

2022-02-15 16:38 UTC, simonmeggle commented on nagiosplugin/check.py
> +        resource's name. If *name* is None, so prefix is set at all.
I think it's already fixed in 98e786a4, isn't it?

2022-02-15 18:09 UTC, mpounsett approved these changes

2022-02-15 18:09 UTC, merged